
hm_split: val
hm_idx_scene: 00815
hm_scene_name: h1zeeAwLh9Z 
hm_data_version: 1

data_collection:
  init_pos: [0.0, 0.0, 0.0]
  idx_scene: ${hm_idx_scene}
  scene: ${hm_scene_name}
  version: ${hm_data_version}
  sensor_wc:
    translation: [0.0, 0.0, 0.0]
    rotation: [180, 0, 0] 
  max_distance: 2.0
  min_count_px_semantic: 500
  saved_dir: ${data_dir}/${data_collection.idx_scene}-${data_collection.scene}_${data_collection.version}
  position_fn: ${data_collection.saved_dir}/hm_states.txt
  semantic_fn: ${data_collection.saved_dir}/semantics.txt
  cfg_fn: ${data_collection.saved_dir}/cfg.yaml
  color_sensor: color_sensor
  depth_sensor: depth_sensor
  semantic_sensor: semantic_sensor
