seed: 10
defaults:
  - general
  - _self_

hm3d_dir: /media/datasets/habitat/v0.2/
data_dir: /media/datasets/hm_semantic_maps/data_collection_default

hm_split: val
hm_idx_scene: 00815
hm_scene_name: h1zeeAwLh9Z 
hm_data_version: 1


habitat:
  scene: ${hm3d_dir}/${hm_split}/${hm_idx_scene}-${hm_scene_name}/${hm_scene_name}.basis.glb
  scene_dataset_config_file: ${hm3d_dir}/${hm_split}/hm3d_annotated_${hm_split}_basis.scene_dataset_config.json
  width: 1024
  height: 512
  hfov: 120
  sensor_height: 0.0
  enable_physics: False
  agent_radius: 0
  # sensors
  color_sensor: True  
  depth_sensor: True
  semantic_sensor: True
  ortho_rgba_sensor: False
  ortho_depth_sensor: False
  ortho_semantic_sensor: False
  equirect_rgba_sensor: False
  equirect_depth_sensor: False
  equirect_semantic_sensor: False
  fisheye_rgba_sensor: False
  fisheye_depth_sensor: False
  actions: ${default_actions}

default_actions:
  look_up: 5
  look_down: 5
  move_up: 0.15
  move_down: 0.15
  move_forward: 0.25
  move_backward: 0.25
  move_left: 0.25
  move_right: 0.25
  turn_left: 10.0
  turn_right: 10.0
