
hm_split: val
hm_idx_scene: 00815
hm_scene_name: h1zeeAwLh9Z 
hm_data_version: 1

hm_data:
  init_pos: [0.0, 0.0, 0.0]
  init_rot: [1, 0, 0, 0]
  idx_scene: ${hm_idx_scene}
  scene: ${hm_scene_name}
  version: ${hm_data_version}
  max_distance: 2.0
  min_count_px_semantic: 500
  saved_dir: ${data_dir}/${hm_data.idx_scene}-${hm_data.scene}_${hm_data.version}
  hm_actions_fn: ${hm_data.saved_dir}/hm_actions.txt
  poses_dir: ${hm_data.saved_dir}/poses
  rgb_dir: ${hm_data.saved_dir}/rgb
  depth_dir: ${hm_data.saved_dir}/depth
  semantic_dir: ${hm_data.saved_dir}/semantic
  semantic_fn: ${hm_data.saved_dir}/semantics.txt
  cfg_fn: ${hm_data.saved_dir}/cfg.yaml
  color_sensor: color_sensor
  depth_sensor: depth_sensor
  semantic_sensor: semantic_sensor
  bins_voxel_map_3d_fn: ${hm_data.saved_dir}/bins_voxel_map_3d.npy
  bins_voxel_map_2d_fn: ${hm_data.saved_dir}/bins_voxel_map_2d.npy

log_dir: ${hm_data.saved_dir}/logs/

voxel_grid_2d:
  voxel_type: voxel_grid_2d
  grid_size: 0.05
  padding: 10

voxel_grid_3d:
  voxel_type: voxel_grid_3d
  grid_size: 0.05
  padding: 10
